version: '3.1'

networks:
    inception:
        driver: bridge

services:
  mariadb:
    container_name: mariadb
    hostname: mariadb
    build:
      context: ./requirements/mariadb
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    expose:
      - 3306
    networks:
      - inception
  nginx:
    container_name: nginx
    hostname: nginx
    build:
      context: ./requirements/nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpressdb:/var/www/html/wordpress
    env_file:
      - .env
    networks:
      - inception
  wordpress:
    container_name: wordpress
    hostname: wordpress
    build:
      context: ./requirements/wordpress
    restart: always
    volumes:
      - wordpressdb:/var/www/html/wordpress
    env_file:
      - .env
    networks:
      - inception
    expose:
      - 9000
    tty: true

volumes:
    mariadb:
    wordpressdb: