version: '3.8'

networks:
    inception:
        driver: bridge

services:
  mariadb:
    build:
      context: ./requirements/mariadb
    restart: always
    volumes:
      - type: bind
        source: /home/vboxuser/data/mariadb
        target: /var/lib/mysql
    env_file:
      - .env
    expose:
      - 3306
    networks:
      - inception
  nginx:
    build:
      context: ./requirements/nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - type: bind
        source: /home/vboxuser/data/wordpress
        target: /var/www/html/wordpress
    env_file:
      - .env
    networks:
      - inception
  wordpress:
    build:
      context: ./requirements/wordpress
    restart: always
    volumes:
      - type: bind
        source: /home/vboxuser/data/wordpress
        target: /var/www/html/wordpress
    env_file:
      - .env
    networks:
      - inception
    expose:
      - 9000
    tty: true