version: '3.1'

networks:
  inception: {}

services:
  mariadb: #컨테이너 명
    build:
      context: ./requirements/mariadb/.
    restart: always
    volumes:
      - mariadbdb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    tty: true
    expose:
      - 3306


  nginx:
    build:
      context: ./requirements/nginx/.
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpressdb:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    tty: true


  wordpress:
    build:
      context: ./requirements/wordpress/.
    restart: always
    volumes:
      - wordpressdb:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    expose:
      - 9000
    tty: true

volumes:
    mariadbdb:
    wordpressdb: